#!/usr/bin/env python
# coding: utf-8

#source https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi?chapter=tgencodes

__author__ = "Guisen Chen <thecgs001@foxmil.com>"
__all__ = ['getCodonTable', 'CodonTable']

CodonTable1=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C', 
             'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C', 
             'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': '.', 
             'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W', 
             'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R', 
             'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R', 
             'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R', 
             'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R', 
             'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S', 
             'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S', 
             'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R', 
             'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R', 
             'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G', 
             'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G', 
             'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G', 
             'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], ['TAA', 'TGA', 'TAG']]

CodonTable2=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C', 
             'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C', 
             'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': 'W', 
             'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W', 
             'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R', 
             'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R', 
             'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R', 
             'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R', 
             'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S', 
             'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S', 
             'ATA': 'M', 'ACA': 'T', 'AAA': 'K', 'AGA': '.', 
             'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': '.', 
             'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G', 
             'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G', 
             'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G', 
             'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATA', 'ATG', 'ATT', 'ATC'], ['TAA', 'TAG', 'AGA', 'AGG']]

CodonTable3=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C', 
             'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C', 
             'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': 'W', 
             'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W', 
             'CTT': 'T', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R', 
             'CTC': 'T', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R', 
             'CTA': 'T', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R', 
             'CTG': 'T', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R', 
             'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S', 
             'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S', 
             'ATA': 'M', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R', 
             'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R', 
             'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G', 
             'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G', 
             'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G', 
             'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATA', 'ATG'], ['TAA', 'TAG']]

CodonTable4=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C', 
             'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C', 
             'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': 'W', 
             'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W', 
             'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R', 
             'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R', 
             'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R', 
             'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R', 
             'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S', 
             'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S', 
             'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R', 
             'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R', 
             'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G', 
             'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G', 
             'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G', 
             'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['TTA', 'TTG', 'CTG', 'ATT', 'ATA', 'ATG', 'ATC', 'GTG', 'GTA'], ['TAA', 'TAG']]

CodonTable5=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C', 
             'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C', 
             'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': 'W', 
             'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W', 
             'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R', 
             'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R', 
             'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R', 
             'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R', 
             'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S', 
             'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S', 
             'ATA': 'M', 'ACA': 'T', 'AAA': 'K', 'AGA': 'S', 
             'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'S', 
             'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G', 
             'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G', 
             'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G', 
             'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['AGG', 'ATA', 'ATG'], ['TAA', 'TAG']]

CodonTable6=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C', 
             'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C', 
             'TTA': 'L', 'TCA': 'S', 'TAA': 'Q', 'TGA': '.', 
             'TTG': 'L', 'TCG': 'S', 'TAG': 'Q', 'TGG': 'W', 
             'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R', 
             'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R', 
             'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R', 
             'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R', 
             'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S', 
             'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S', 
             'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R', 
             'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R', 
             'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G', 
             'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G', 
             'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G', 
             'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG','ATA','ATT','ATC','GTG','TTG'], ['TGA']]

CodonTable9=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C', 
             'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C', 
             'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': 'W', 
             'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W', 
             'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R', 
             'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R', 
             'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R', 
             'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R', 
             'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S', 
             'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S', 
             'ATA': 'I', 'ACA': 'T', 'AAA': 'N', 'AGA': 'S', 
             'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'S', 
             'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G', 
             'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G', 
             'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G', 
             'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], ['TAA', 'TAG']]

CodonTable10=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': 'C',
              'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], ['TAA']]

CodonTable11=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': '.',
              'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], ['TAA', 'TGA', 'TAG']]

CodonTable12=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': '.',
              'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'S', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG','CTG'], ['TAA', 'TGA', 'TAG']]

CodonTable13=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': 'W',
              'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'M', 'ACA': 'T', 'AAA': 'K', 'AGA': 'G',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'G',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATA', 'GTG', 'TTG'], ['TAA', 'TAG']]

CodonTable14=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': 'Y', 'TGA': 'W',
              'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'N', 'AGA': 'S',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'S',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], ['TAG']]

CodonTable16=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': '.',
              'TTG': 'L', 'TCG': 'S', 'TAG': 'L', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], ['TAA', 'TGA']]

CodonTable21=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': 'W',
              'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'M', 'ACA': 'T', 'AAA': 'N', 'AGA': 'S',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'S',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], ['TAA', 'TAG']]

CodonTable22=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': '.', 'TAA': '.', 'TGA': '.',
              'TTG': 'L', 'TCG': 'S', 'TAG': 'L', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], ['TAA', 'TGA']]

CodonTable23=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': '.', 'TCA': 'S', 'TAA': '.', 'TGA': '.',
              'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], ['TAA', 'TAG', 'TGA']]

CodonTable24=[{'TTT': 'F', 'TCT': 'S',  'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S',  'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S',  'TAA': '.', 'TGA': 'W',
              'TTG': 'L', 'TCG': 'S',  'TAG': '.', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P',  'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P',  'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P',  'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P',  'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T',  'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T',  'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T',  'AAA': 'K', 'AGA': 'S',
              'ATG': 'M', 'ACG': 'T',  'AAG': 'K', 'AGG': 'K',
              'GTT': 'V', 'GCT': 'A',  'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A',  'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A',  'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A',  'GAG': 'E', 'GGG': 'G'}, ['ATG'], ['TAA', 'TAG']]

CodonTable25=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': 'G',
              'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG', 'GTG', 'TTG'], ['TAA', 'TAG']]

CodonTable26=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': '.', 'TGA': '.',
              'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'A', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG', 'GTG', 'TTG'], ['TAA', 'TAG', 'TGA']]

CodonTable27=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': 'Q', 'TGA': 'W',
              'TTG': 'L', 'TCG': 'S', 'TAG': 'Q', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], []]

CodonTable28=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': 'Q', 'TGA': 'W',
              'TTG': 'L', 'TCG': 'S', 'TAG': 'Q', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], []]

CodonTable29=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': 'Y', 'TGA': '.',
              'TTG': 'L', 'TCG': 'S', 'TAG': 'Y', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], ['TGA']]

CodonTable30=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': 'E', 'TGA': '.',
              'TTG': 'L', 'TCG': 'S', 'TAG': 'E', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], ['TGA']]

CodonTable31=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': 'E', 'TGA': 'W',
              'TTG': 'L', 'TCG': 'S', 'TAG': 'E', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'R',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'R',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], []]

CodonTable33=[{'TTT': 'F', 'TCT': 'S', 'TAT': 'Y', 'TGT': 'C',
              'TTC': 'F', 'TCC': 'S', 'TAC': 'Y', 'TGC': 'C',
              'TTA': 'L', 'TCA': 'S', 'TAA': 'Y', 'TGA': 'W',
              'TTG': 'L', 'TCG': 'S', 'TAG': '.', 'TGG': 'W',
              'CTT': 'L', 'CCT': 'P', 'CAT': 'H', 'CGT': 'R',
              'CTC': 'L', 'CCC': 'P', 'CAC': 'H', 'CGC': 'R',
              'CTA': 'L', 'CCA': 'P', 'CAA': 'Q', 'CGA': 'R',
              'CTG': 'L', 'CCG': 'P', 'CAG': 'Q', 'CGG': 'R',
              'ATT': 'I', 'ACT': 'T', 'AAT': 'N', 'AGT': 'S',
              'ATC': 'I', 'ACC': 'T', 'AAC': 'N', 'AGC': 'S',
              'ATA': 'I', 'ACA': 'T', 'AAA': 'K', 'AGA': 'S',
              'ATG': 'M', 'ACG': 'T', 'AAG': 'K', 'AGG': 'K',
              'GTT': 'V', 'GCT': 'A', 'GAT': 'D', 'GGT': 'G',
              'GTC': 'V', 'GCC': 'A', 'GAC': 'D', 'GGC': 'G',
              'GTA': 'V', 'GCA': 'A', 'GAA': 'E', 'GGA': 'G',
              'GTG': 'V', 'GCG': 'A', 'GAG': 'E', 'GGG': 'G'}, ['ATG'], ['TAG']]

CodonTable = {'CodonTable1':(CodonTable1, ['Standard']),
              'CodonTable2':(CodonTable2, ['Vertebrate Mitochondrial']),
              'CodonTable3':(CodonTable3, ['YeastMitochondrial']),
              'CodonTable4':(CodonTable4, ['Mold Mitochondrial', 'Protozoan Mitochondrial', 'Coelenterate Mitochondrial', 'Mycoplasma', 'Spiroplasma']),
              'CodonTable5':(CodonTable5, ['Invertebrate Mitochondrial']),
              'CodonTable6':(CodonTable6, ['Ciliate Nuclear','Dasycladacean Nuclear', 'Hexamita Nuclear']),
              'CodonTable9':(CodonTable9, ['Echinoderm Mitochondrial', 'Flatworm Mitochondrial']),
              'CodonTable10':(CodonTable10, ['Euplotid Nuclear']),
              'CodonTable11':(CodonTable11, ['Bacterial','Archaeal','Plant Plastid']),
              'CodonTable12':(CodonTable12, ['Alternative Yeast Nuclear']),
              'CodonTable13':(CodonTable13, ['Ascidian Mitochondrial']),
              'CodonTable14':(CodonTable14, ['Alternative Flatworm Mitochondrial']),
              'CodonTable16':(CodonTable16, ['Chlorophycean Mitochondrial']),
              'CodonTable21':(CodonTable21, ['Trematode Mitochondrial']),
              'CodonTable22':(CodonTable22, ['Scenedesmus obliquus Mitochondrial']),
              'CodonTable23':(CodonTable23, ['Thraustochytrium Mitochondrial']),
              'CodonTable24':(CodonTable24, ['Rhabdopleuridae Mitochondrial']),
              'CodonTable25':(CodonTable25, ['Candidate Division SR1', 'Gracilibacteria']),
              'CodonTable26':(CodonTable26, ['Pachysolen tannophilus Nuclear']),
              'CodonTable27':(CodonTable27, ['Karyorelict Nuclear']),
              'CodonTable28':(CodonTable28, ['Condylostoma Nuclear']),
              'CodonTable29':(CodonTable29, ['Mesodinium Nuclear']),
              'CodonTable30':(CodonTable30, ['Peritrich Nuclear']),
              'CodonTable31':(CodonTable31, ['Blastocrithidia Nuclear']),
              'CodonTable33':(CodonTable33, ['Cephalodiscidae Mitochondrial UAA-Tyr'])}

def getCodonTable(arg=1):
    arg = str(arg).strip()
    try:
        int(arg)
        key = f"CodonTable{int(arg)}"
        res = CodonTable[key][0]
        return res
    except:
        for key in CodonTable:
            if arg in CodonTable[key][1] or arg.replace('_',' ', 1) in CodonTable[key][1] or arg.replace('-',' ', 1) in CodonTable[key][1]:
                res = CodonTable[key][0]
                return res
